# Configuração do Blog
server {
    listen 80;
    server_name blog.techvision.local;

    location / {
        root /usr/share/nginx/html/blog;
        index index.html;
    }
}

# Configuração da Documentação
server {
    listen 80;
    server_name docs.techvision.local;

    location / {
        root /usr/share/nginx/html/docs;
        index index.html;
    }
}